import { describe, expect, it } from 'vitest';
import * as analyze from '../src/analyze/index.js';
import * as core from '../src/core/index.js';
import * as generate from '../src/generate/index.js';
import * as api from '../src/index.js';
import * as model from '../src/model/index.js';
import * as theory from '../src/theory/index.js';

/**
 * Guards the public runtime surface against accidental loss during refactors.
 * When an export is intentionally renamed or removed, update this list in the
 * same commit so the diff reads as the rename table itself.
 */
const EXPECTED_EXPORTS = [
  'ALGORITHM_VERSION',
  'ALTERED_MASK',
  'ARTICULATIONS',
  'BAR_STEPS',
  'BASS_4_STRING',
  'BASS_5_STRING',
  'BASS_LICKS',
  'BASS_STYLES',
  'BEAT_STEPS',
  'BLUES_MASK',
  'BORROWED_DEGREES',
  'BudgetExceededError',
  'CHROMATIC_MASK',
  'Chord',
  'ConsonanceClass',
  'DEFAULT_GENERATION_BUDGET',
  'DORIAN_MASK',
  'DOUBLE_HARMONIC_MASK',
  'DRUM_KIT',
  'DRUM_NOTES',
  'DRUM_PATTERNS',
  'FILL_ARCHETYPES',
  'FILL_TYPES',
  'GENRES',
  'GUITAR_DROP_D',
  'GUITAR_STANDARD',
  'HARMONIC_MINOR_MASK',
  'Interval',
  'InvalidInputError',
  'JUST_RATIOS',
  'KICK_FIGURES',
  'KICK_STEPS',
  'Key',
  'LIMBS',
  'LOCRIAN_MASK',
  'LOCRIAN_NATURAL2_MASK',
  'LYDIAN_DOMINANT_MASK',
  'LYDIAN_MASK',
  'MAJOR_MASK',
  'MAJOR_PENTATONIC_MASK',
  'MARWA_MASK',
  'MAX_DIFFICULTY',
  'MELODIC_MINOR_MASK',
  'MINOR_PENTATONIC_MASK',
  'MIN_ALGORITHM_VERSION',
  'MIN_DIFFICULTY',
  'MIXOLYDIAN_B13_MASK',
  'MIXOLYDIAN_MASK',
  'MIYAKO_BUSHI_MASK',
  'MODAL_SCALE_NAMES',
  'NAMED_SCALES',
  'NATURAL_MINOR_MASK',
  'NOTE_VALUES',
  'NoSolutionError',
  'Note',
  'NoteSafety',
  'OCTATONIC_HALF_WHOLE_MASK',
  'OCTATONIC_WHOLE_HALF_MASK',
  'ORNAMENT_STYLES',
  'PHRYGIAN_DOMINANT_MASK',
  'PHRYGIAN_MASK',
  'PROFILE_WEIGHTS',
  'PROVENANCE_BASES',
  'PURVI_MASK',
  'Progression',
  'RITSU_MASK',
  'RYUKYU_MASK',
  'ReasonFlag',
  'SATB_RANGES',
  'SCALE_ALIASES',
  'SCALE_SYSTEMS',
  'STEP_BEATS',
  'TODI_MASK',
  'TRANSPOSING_INSTRUMENTS',
  'TWELVE_TET',
  'WHOLE_TONE_MASK',
  'WORLD_SCALES',
  'analyzeArrangement',
  'analyzeChord',
  'analyzeVoice',
  'applyGrooveTemplate',
  'assertDegree',
  'assertFiniteNumber',
  'assertFiniteSemitones',
  'assertGenerationBudget',
  'assertInteger',
  'assertMeterMap',
  'assertMidiPitch',
  'assertNoteEvent',
  'assertNoteEvents',
  'assertOneOf',
  'assertPositiveInt',
  'assertRange',
  'assertTimeSignature',
  'assertVocabulary',
  'augmentedSixthChord',
  'augmentedSixthKind',
  'availableTensions',
  'avoidNotes',
  'barIndexAt',
  'barPositionToBeat',
  'barPositionToPulse',
  'barStartBeat',
  'beatToBarPosition',
  'beatsPerBar',
  'beatsPerBarAt',
  'beatsToDuration',
  'beatsToSeconds',
  'beatsToTicks',
  'beatsToTiedDurations',
  'borrowedSource',
  'canSound',
  'centsBetweenFreq',
  'centsFromNearestStep',
  'centsOfSteps',
  'centsToRatio',
  'checkPartWriting',
  'checkSpecies',
  'chordFromDegree',
  'chordFromSpan',
  'chordFromSpec',
  'chordPitchClasses',
  'chordQualities',
  'chordScaleReport',
  'chordScales',
  'chordSpecIntervals',
  'chordSpecOf',
  'chordSpecQuality',
  'chordTimelineFromChords',
  'chordTimelineFromNotes',
  'chordToRoman',
  'chordToneRole',
  'clampToMidi',
  'classifyInterval',
  'classifyMelodyTones',
  'classifySpelledInterval',
  'compareMelodies',
  'createArrangementSession',
  'createNoteEventIndex',
  'createPositionalRng',
  'createRng',
  'createsBattuta',
  'createsHiddenParallelPerfect',
  'createsParallelOctave',
  'createsParallelPerfect',
  'createsParallelUnison',
  'createsVerticalDissonance',
  'createsVoiceCrossing',
  'createsVoiceOverlap',
  'deform',
  'deriveSeed',
  'detectCadence',
  'detectCadences',
  'detectChord',
  'detectChordBest',
  'detectKey',
  'detectKeyBest',
  'detectKeyFromNotes',
  'detectModulations',
  'detectNoteNameSystem',
  'developMotif',
  'diatonicLetterOf',
  'diatonicPitchClasses',
  'diatonicSeventh',
  'diatonicTriad',
  'dominantKeyOf',
  'double',
  'doubleTime',
  'dropSilentNotes',
  'drumVoiceOf',
  'durationToBeats',
  'durationToSeconds',
  'edo',
  'enharmonicKeyOf',
  'enumerateSafePitches',
  'evaluateSafety',
  'exceedsSpacing',
  'explainRoman',
  'extractGrooveTemplate',
  'extractMotifs',
  'figuredBassOf',
  'figuredBassRealization',
  'fingeringsFor',
  'fitsQuery',
  'foldIntoRange',
  'formatBarPosition',
  'formatChordSymbol',
  'formatKeyName',
  'formatNote',
  'formatTimeSignature',
  'frequencyOf',
  'functionOf',
  'generateBassLine',
  'generateCounterMelody',
  'generateDrums',
  'generateMotif',
  'generateProgression',
  'generateRhythm',
  'halfTime',
  'harmonizeMelody',
  'humanize',
  'hypermeter',
  'imitate',
  'includeAt',
  'instrumentRange',
  'instrumentTransposition',
  'intervalAboveRoot',
  'intervalSemitones',
  'isAugmentedMelodicInterval',
  'isBorrowedChord',
  'isChordMember',
  'isCompound',
  'isConsonantInterval',
  'isDiatonic',
  'isDrumPattern',
  'isFillArchetype',
  'isForbiddenMelodicLeap',
  'isLeadingToneResolution',
  'isLibcantusError',
  'isLickMaterial',
  'isMinorKey',
  'isPerfectInterval',
  'isScaleTone',
  'isStrongBeat',
  'justDeviationCents',
  'keyFromFifths',
  'keyRelationBetween',
  'keySignatureFifths',
  'keyTimelineFromNotes',
  'majorKey',
  'makeChord',
  'maskFromOffsets',
  'melodicContour',
  'melodicSimilarity',
  'mergeVocabulary',
  'meterAt',
  'metricWeight',
  'midiToNote',
  'minorKey',
  'modalInterchangePalette',
  'motifFromNotes',
  'motifToNoteEvents',
  'namedScaleMask',
  'naturalPitchClassOf',
  'nearestScaleTone',
  'nearestStep',
  'negativeHarmonyMirror',
  'nextVoicing',
  'noteNames',
  'noteToMidi',
  'noteToPitchClass',
  'onsetWeightCurve',
  'ornament',
  'ornamentBy',
  'parallelKey',
  'parallelKeyOf',
  'parseChordSymbol',
  'parseInterval',
  'parseKeyName',
  'parseNote',
  'parseTimeSignature',
  'phrasesFromTimeline',
  'pickProgressionPreset',
  'pickVocabulary',
  'pitchClassOf',
  'pitchToScaleDegree',
  'pivotChords',
  'placeDrumPattern',
  'placeLicks',
  'playability',
  'prevailingKeyOf',
  'profileWeights',
  'progressions',
  'progressionsByStyle',
  'pulseBeats',
  'pulsesPerBar',
  'ratioToCents',
  'realizeFiguredBass',
  'reduceProgression',
  'relateMotifs',
  'relatedKeysOf',
  'relativeKeyOf',
  'requireScaleMask',
  'resolveAlgorithmVersion',
  'resolveContext',
  'resolveMeters',
  'resolveScaleName',
  'rhythmDensity',
  'rhythmToNoteEvents',
  'roleOf',
  'romanToChord',
  'scaleByName',
  'scaleMatchesChord',
  'scaleSystemOf',
  'scaleTonesInDegreeOrder',
  'scalesForChanges',
  'secondaryDominant',
  'secondaryDominantOf',
  'secondsToBeats',
  'sectionsFromNotes',
  'selectVocabulary',
  'soundingNotesOnly',
  'spanFromChord',
  'spellAugmentedSixth',
  'spellChord',
  'spellChordFromRoot',
  'spellLine',
  'spellPitch',
  'spellPitchClass',
  'spellPitchClasses',
  'spellScale',
  'spellVoicing',
  'spelledInterval',
  'spelledKeyOf',
  'stepOf',
  'stepsOfCents',
  'structuralCadences',
  'subdominantKeyOf',
  'substituteChord',
  'supportsFunctionalHarmony',
  'sustainsShift',
  'sustainsStrokes',
  'syncopate',
  'tempoAt',
  'tensionCurve',
  'tensionCurveFrom',
  'thin',
  'ticksToBeats',
  'toSoundingPitch',
  'toSpelledInterval',
  'toVoiceNotes',
  'toWrittenPitch',
  'transformMotif',
  'transposeByInterval',
  'transposeChord',
  'transposeChordSymbol',
  'transposeNote',
  'tryParseChordSymbol',
  'tryParseInterval',
  'tryParseNote',
  'tuplet',
  'vocabularyOfKind',
  'voiceChord',
  'voiceChordStyled',
  'voiceIndependence',
  'voiceLeadingCost',
  'voiceProgression',
  'withinCeiling',
];

/** Every layer barrel, in the order the root re-exports them. */
const LAYERS = { core, theory, analyze, generate, model } as const;

describe('public API surface', () => {
  it('exports exactly the expected runtime members', () => {
    const actual = Object.keys(api).sort();
    expect(actual).toEqual([...EXPECTED_EXPORTS].sort());
  });

  it('reaches every root member through the layer subpath that owns it', () => {
    // Derived rather than listed: the root barrel is five `export *` lines, so
    // a name the root still has but a layer barrel lost is a subpath consumer's
    // break that the root-only list above cannot see.
    const fromLayers = new Set(Object.values(LAYERS).flatMap((layer) => Object.keys(layer)));
    expect([...Object.keys(api)].filter((name) => !fromLayers.has(name))).toEqual([]);
    expect([...fromLayers].filter((name) => !(name in api)).sort()).toEqual([]);
  });

  it('keeps the model API aligned with its functional counterparts', () => {
    const key = model.Key.major('C');
    const chord = key.roman('V7/V');
    const progression = new model.Progression([chord, key.roman('V7'), key.roman('I')], key);
    const romanOpts = { applied: true };

    expect(chord.roman(undefined, romanOpts)).toBe(
      api.chordToRoman(chord.data, key.scale, romanOpts),
    );
    expect(progression.analyze(undefined, romanOpts).chords).toEqual(
      progression.chords.map((item) => api.analyzeChord(item.data, key.scale, romanOpts)),
    );
    expect(progression.scales()).toEqual(
      api.scalesForChanges(progression.chords.map((item) => item.data)),
    );

    const pitches = [57, 59, 60, 62, 64, 65, 68];
    expect(model.Key.detectMatches(pitches)).toEqual(
      api.detectKey(pitches).map((match) => ({
        ...match,
        key: expect.objectContaining({
          scale: match.key,
          variant: match.variant,
        }),
      })),
    );
  });
});
