/**
 * Reharmonization: chord substitution, modal-interchange palettes, and negative
 * harmony. These transforms take an existing chord (or a key) and propose
 * alternative harmonies that preserve a chosen relationship — a shared function,
 * a common tone, a tonicizing dominant, or a reflection across the key axis.
 *
 * Roots are pitch classes (0..11); no spelled key signature is required.
 */

import { detectChordBest } from '../../analyze/detect/index.js';
import {
  type BorrowedSource,
  borrowedSource,
  chordToRoman,
  functionOf,
  type HarmonicFunction,
  isDiatonic,
  parallelKey,
} from '../../analyze/functional/index.js';
import { pitchClassOf as mod12 } from '../../core/pitch/index.js';
import type { KeyScale } from '../../core/types.js';
import {
  type Chord,
  type ChordQuality,
  chordPitchClasses,
  diatonicTriad,
  makeChord,
} from '../../theory/chord/index.js';
import { scaleTonesInDegreeOrder } from '../../theory/scale/index.js';

/**
 * The kind of substitution relationship a candidate realizes.
 *
 * @category Reharmonization
 */
export type SubstitutionType =
  | 'tritone'
  | 'relative'
  | 'borrowed'
  | 'chromaticMediant'
  | 'secondaryDominant';

/**
 * A proposed chord substitution with its relationship, numeral, and function.
 *
 * @category Reharmonization
 */
export type Substitution = {
  chord: Chord;
  type: SubstitutionType;
  roman: string;
  function: HarmonicFunction;
};

/**
 * Options controlling which substitutions {@link substituteChord} returns.
 *
 * @category Reharmonization
 */
export type SubstituteOptions = {
  /**
   * Melody pitch classes that must remain chord tones. When given, only
   * substitutions whose pitch classes contain every listed pitch class are
   * kept, so the melody stays consonant against the new harmony.
   */
  melodyPcs?: number[];
};

/** Whether the chord's template carries a given interval (mod 12). */
function hasInterval(chord: Chord, semitone: number): boolean {
  return chord.intervals.some((iv) => mod12(iv) === semitone);
}

/** Whether a chord is a dominant type: a major third with a minor seventh. */
function isDominantType(chord: Chord): boolean {
  return hasInterval(chord, 4) && hasInterval(chord, 10);
}

/** Count the pitch classes shared between two pitch-class sets. */
function commonToneCount(a: number[], b: number[]): number {
  const set = new Set(b);
  return a.filter((pc) => set.has(pc)).length;
}

/** The plain triad quality underlying a chord's own quality. */
function triadQualityOf(chord: Chord): ChordQuality {
  const semis = new Set(chord.intervals.map((interval) => mod12(interval)));
  const hasThird = semis.has(4) ? 'maj' : semis.has(3) ? 'min' : undefined;
  if (hasThird === undefined) {
    return chord.quality; // sus, power, and other non-tertian chords stand alone
  }
  if (semis.has(6) && !semis.has(7)) {
    return hasThird === 'min' ? 'dim' : 'majb5';
  }
  if (semis.has(8) && !semis.has(7)) {
    return 'aug';
  }
  return hasThird;
}

/** The diatonic triads of a key, one per scale degree. */
function diatonicTriadsOf(key: KeyScale): Chord[] {
  const degrees = scaleTonesInDegreeOrder(key).length;
  const triads: Chord[] = [];
  for (let degree = 0; degree < degrees; degree += 1) {
    triads.push(diatonicTriad(degree, key));
  }
  return triads;
}

/** Whether two chords share the same root pitch class and quality. */
function sameChord(a: Chord, b: Chord): boolean {
  return mod12(a.rootPc) === mod12(b.rootPc) && a.quality === b.quality;
}

/** Root offsets (semitones) that form a third above or below a root. */
const THIRD_OFFSETS = [3, 4, 8, 9] as const;

/**
 * Propose substitutions for a chord within a key.
 *
 * Candidates are generated by several relationships and deduplicated against the
 * original chord and each other:
 *
 * - `tritone`: for a dominant-type chord, the dominant seventh a tritone away.
 * - `relative`: a diatonic triad a third away that shares two common tones.
 * - `borrowed`: a triad from the parallel mode with the same harmonic function.
 * - `chromaticMediant`: a major/minor triad a third away sharing one common
 *   tone.
 *
 * Each result carries its Roman numeral and harmonic function in `key`. When
 * `opts.melodyPcs` is given, only substitutions whose pitch classes contain all
 * of those pitch classes are returned.
 *
 * @param chord The chord to reharmonize.
 * @param key The prevailing key.
 * @param opts Optional melody-preservation constraint.
 * @returns The deduplicated substitution candidates.
 * @example
 * ```ts
 * import { substituteChord, makeChord, majorKey } from '@libraz/libcantus';
 * const subs = substituteChord(makeChord(7, 'dom7'), majorKey(0));
 * // includes the tritone sub Db7 (rootPc 1, quality 'dom7')
 * ```
 * @category Reharmonization
 */
export function substituteChord(
  chord: Chord,
  key: KeyScale,
  opts?: SubstituteOptions,
): Substitution[] {
  // The relative test counts common tones against the chord's triad, not its
  // full pitch-class set: an exact count of two would otherwise be decided by
  // how many tensions the input carries, so C proposes both Em and Am while
  // Cmaj7 proposes only Am — penalising the candidate that overlaps *more*.
  const originalTriad = chordPitchClasses(makeChord(chord.rootPc, triadQualityOf(chord)));
  const candidates: { chord: Chord; type: SubstitutionType }[] = [];

  // Tritone substitution: only for dominant-type chords.
  if (isDominantType(chord)) {
    candidates.push({ chord: makeChord(mod12(chord.rootPc + 6), 'dom7'), type: 'tritone' });
  }

  // Relative: a diatonic triad a third away sharing two common tones.
  for (const triad of diatonicTriadsOf(key)) {
    const offset = mod12(triad.rootPc - chord.rootPc);
    if (
      (THIRD_OFFSETS as readonly number[]).includes(offset) &&
      commonToneCount(originalTriad, chordPitchClasses(triad)) === 2
    ) {
      candidates.push({ chord: triad, type: 'relative' });
    }
  }

  // Borrowed: a parallel-mode triad sharing the original's harmonic function.
  const targetFunction = functionOf(chord, key);
  for (const triad of diatonicTriadsOf(parallelKey(key))) {
    if (functionOf(triad, key) === targetFunction && !isDiatonic(triad, key)) {
      candidates.push({ chord: triad, type: 'borrowed' });
    }
  }

  // Chromatic mediants: major/minor triads a third away sharing one common tone.
  for (const offset of THIRD_OFFSETS) {
    for (const quality of ['maj', 'min'] as const) {
      const mediant = makeChord(mod12(chord.rootPc + offset), quality);
      if (
        commonToneCount(originalTriad, chordPitchClasses(mediant)) === 1 &&
        !isDiatonic(mediant, key)
      ) {
        candidates.push({ chord: mediant, type: 'chromaticMediant' });
      }
    }
  }

  const melodyPcs = opts?.melodyPcs?.map(mod12);
  const seen = new Set<string>();
  const results: Substitution[] = [];
  for (const candidate of candidates) {
    if (sameChord(candidate.chord, chord)) {
      continue;
    }
    const dedupeKey = `${mod12(candidate.chord.rootPc)}:${candidate.chord.quality}`;
    if (seen.has(dedupeKey)) {
      continue;
    }
    seen.add(dedupeKey);
    if (melodyPcs !== undefined) {
      const pcs = new Set(chordPitchClasses(candidate.chord));
      if (!melodyPcs.every((pc) => pcs.has(pc))) {
        continue;
      }
    }
    results.push({
      chord: candidate.chord,
      type: candidate.type,
      // A secondary dominant is named as the applied chord it is, so the
      // numeral re-parses to the chord that was proposed rather than to a
      // chromatic chord on the same root.
      roman: chordToRoman(candidate.chord, key, {
        applied: candidate.type === 'secondaryDominant',
      }),
      function: functionOf(candidate.chord, key),
    });
  }
  return results;
}

/**
 * A borrowed chord in the modal-interchange palette of a key.
 *
 * @category Reharmonization
 */
export type BorrowedChord = {
  chord: Chord;
  roman: string;
  source: BorrowedSource;
};

/**
 * The modal-interchange palette of a key.
 *
 * Lists the diatonic triads of the {@link parallelKey} that are not diatonic to
 * `key` (the classic borrowed chords such as `iv`, `bVI`, and `bVII` in a major
 * key), plus the Neapolitan (a major triad on the flat second degree). Each
 * carries its Roman numeral and {@link borrowedSource} relative to `key`.
 *
 * @param key The prevailing key.
 * @returns The borrowed-chord palette.
 * @category Reharmonization
 */
export function modalInterchangePalette(key: KeyScale): BorrowedChord[] {
  const palette: BorrowedChord[] = [];
  const seen = new Set<string>();
  const add = (chord: Chord) => {
    const dedupeKey = `${mod12(chord.rootPc)}:${chord.quality}`;
    if (seen.has(dedupeKey)) {
      return;
    }
    seen.add(dedupeKey);
    palette.push({
      chord,
      roman: chordToRoman(chord, key),
      source: borrowedSource(chord, key),
    });
  };

  for (const triad of diatonicTriadsOf(parallelKey(key))) {
    if (!isDiatonic(triad, key) && borrowedSource(triad, key) !== null) {
      add(triad);
    }
  }
  // The Neapolitan (major triad on b2) sits outside both parallel modes, so it
  // is added explicitly — unless b2 is already diatonic (e.g. in a Phrygian key,
  // where it is a native chord rather than a borrowing).
  const neapolitan = makeChord(mod12(key.rootPc + 1), 'maj');
  if (!isDiatonic(neapolitan, key)) {
    add(neapolitan);
  }
  return palette;
}

/**
 * Reflect a chord across the tonic–dominant axis of a key (negative harmony).
 *
 * Every pitch class `p` maps to `(2*T + 7 - p) mod 12`, where `T` is the key
 * tonic — the reflection that swaps the tonic with the dominant. The mirrored
 * pitch classes (including the bass, if set) are reassembled into a chord by
 * {@link detectChordBest}; when no chord is recognized, the mirrored root and
 * the original quality are used as a fallback.
 *
 * @param chord The chord to reflect.
 * @param key The prevailing key.
 * @returns The negative-harmony counterpart of the chord.
 * @example
 * ```ts
 * import { negativeHarmonyMirror, makeChord, majorKey } from '@libraz/libcantus';
 * negativeHarmonyMirror(makeChord(7, 'maj'), majorKey(0));
 * // G major reflected across C's axis => F minor (rootPc 5, quality 'min')
 * ```
 * @category Reharmonization
 */
export function negativeHarmonyMirror(chord: Chord, key: KeyScale): Chord {
  const tonic = mod12(key.rootPc);
  const mirror = (p: number) => mod12(2 * tonic + 7 - p);
  const pcs = chordPitchClasses(chord).map(mirror);
  const bassPc = chord.bassPc !== undefined ? mirror(chord.bassPc) : undefined;
  // Place the mirrored bass an octave below so it is recognized as the lowest
  // note and preserved through detection.
  const pitches = bassPc !== undefined ? [bassPc - 12, ...pcs] : pcs;
  const detected = detectChordBest(pitches);
  if (detected) {
    // Without an input bass the mirrored tones are octave-less, so detection may
    // read the lowest pitch class as a slash bass and report a spurious
    // inversion. Restore the recognized chord to root position in that case.
    if (bassPc === undefined && detected.bassPc !== undefined) {
      return makeChord(detected.rootPc, detected.quality);
    }
    return detected;
  }
  const quality: ChordQuality = chord.quality;
  return makeChord(mirror(chord.rootPc), quality, bassPc);
}
